# Generated by Django 4.1.5 on 2023-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField()),
                ('transaction_at', models.DateField()),
                ('value', models.FloatField()),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('transaction_hour', models.CharField(max_length=6)),
                ('owner', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=19)),
                ('file', models.CharField(max_length=8100, null=True)),
            ],
        ),
    ]
