# Generated by Django 4.1.5 on 2023-01-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField()),
                ('transaction_at', models.DateField()),
                ('value', models.FloatField()),
                ('card', models.CharField(max_length=12)),
                ('transaction_hour', models.CharField(max_length=6)),
                ('file', models.CharField(max_length=8100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='stores.store')),
            ],
        ),
    ]
