# Generated by Django 4.1.5 on 2023-01-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(default='', max_length=8100),
            preserve_default=False,
        ),
    ]
