# Generated by Django 4.1.5 on 2023-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('cpf', models.CharField(max_length=11)),
                ('owner', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=19)),
            ],
        ),
    ]
